### ISSUE TITLE
Nice copied script bro

### ISSUE THREAD

**Issue by CoftSock** [ussrlongbow/chatcom#1]
https://forums.bistudio.com/topic/171047-release-execute-scriptscode-via-chat-commands/

**Comment by ussrlongbow** [comment]
This is not a copy, see the code for very big difference.

**Comment by ussrlongbow** [comment]
Differences:
1. My script uses EH attached to display #46, Conroy's uses loop to check if chat is open
2. My script stores commands configuration in missionConfigFile, Conroy stored them in SQF script.
3. My code is almost twice shorter.

But yes, idea is the same.
